### ISSUE TITLE
Missing file com.ecs.google.maps.v2.actionbarsherlock.R

### ISSUE THREAD

**Issue by tng10** [ddewaele/GoogleMapsV2WithActionBarSherlock#9]
Hi,

I'm following this tutorial but I couldn't find the file <b>com.ecs.google.maps.v2.actionbarsherlock.R;</b>
How can I fix that? Can someone provide this file for me?

Thanks in advance!

**Comment by ddewaele** [comment]
Android studio import should work now ... feel free to comment if it doesn't
